### ISSUE TITLE
Zip Zap Zop?

### ISSUE THREAD

**Issue by rrcobb** [learn-co-curriculum/tf-improv-games#2]
Could be that I am thinking of a similar game, but I remember different rules for Zip-Zap-Zop. 

Zips pass around the circle, Zap reverses direction, Zop goes across the circle, and Boing is the reflector to the Zop. Not sure if I am just remembering wrong, because the rules here also seem familiar. Am I thinking of a different game?

**Comment by AnnJohn** [comment]
Closing issue
